version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: petclinic-postgres
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic_user
      POSTGRES_PASSWORD: petclinic_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - petclinic-net

  tomcat:
    build: .
    image: andreymdster/petclinic:latest
    container_name: petclinic-tomcat
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - petclinic-net

volumes:
  pgdata:

networks:
  petclinic-net:
