name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and redeploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 100.73.135.5
          username: amdudorov
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/devops-java-tomcat-lab/petclinic
            docker compose down || true
            docker compose pull
            docker compose up -d
