name: Manual CI/CD Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR file
        run: |
          ./mvnw clean package -DskipTests

      - name: Move WAR to Docker context
        run: |
          cp target/*.war petclinic.war

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push fr0zen74/petclinic:latest


      - name: Save Docker image as artifact
        run: docker save petclinic-image > petclinic-image.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic-image
          path: petclinic-image.tar
