name: Manual WAR Deploy

on:
  workflow_dispatch:  # 👈 Запуск по кнопке

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build WAR
      run: ./mvnw clean package -DskipTests

    - name: Copy WAR to remote server via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "target/*.war"
        target: "/opt/tomcat/webapps/petclinic.war"

    - name: Restart Tomcat (optional)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          systemctl restart tomcat || systemctl restart tomcat9 || echo "Tomcat restart command skipped"
